### ISSUE TITLE
It's possible for the genetic algorithm to output a best score that's worse than the original config

### ISSUE THREAD

**Issue by erikhuck** [byu-dml/d3m-dynamic-neural-architecture#176]
After writing a test to ensure that the result of the tuning produces an ndcg score that was at least as good as the one for the original config, the test failed. The original config that was put into the tuning algorithm did better than the config that the tuning algorithm output. This was just a unit test though, with only 2 generations and a populations size of 2.

**Comment by bjschoenfeld** [comment]
There are no guarantees that the second generation of tuning will be better than the first.

**Comment by orionw** [comment]
Closing as not an issue: the genetic algorithm makes no guarantees and never actually runs the original config.
