### ISSUE TITLE
Plot predictions vs targets and include scores

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-dynamic-neural-architecture#37]

**Comment by bjschoenfeld** [comment]
Something like these plots on wikipedia: https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient

**Comment by erikhuck** [comment]
A pull request for this issue has been made. It's #40.

**Comment by bjschoenfeld** [comment]
> A pull request for this issue has been made. It's #40.

When you make a pull request, you can reference the issue in the description. Using [this syntax](https://help.github.com/en/articles/closing-issues-using-keywords) will close the issue automatically when the pull request is merged in.
